### ISSUE TITLE
Usermod issue for ansible user

### ISSUE THREAD

**Issue by tony-caffe** [singleplatform-eng/ansible-users#4]
Hi,

 When I run Ansible to make the needed changes to the group of the user that ansible uses, Anthony, It gives me an error. There has to be some fix for this since when running an ad-hoc command to change anything group or user related, it works just fine.

Here is my output:

```
[anthony@woodysbooks-hydra ~]$ ansible-playbook /etc/ansible/playbook/common.yml

PLAY [all] *********************************************************************

TASK [setup] *******************************************************************
ok: [wobo-web1]
ok: [127.0.0.1]

TASK [users : Creating groups] *************************************************
changed: [wobo-web1] => (item={u'gid': 3001, u'name': u'sudo'})
changed: [127.0.0.1] => (item={u'gid': 3001, u'name': u'sudo'})

TASK [users : Per-user group creation] *****************************************
ok: [wobo-web1] => (item={u'username': u'anthony', u'uid': 2001, u'ssh_key': [u'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABA...T2NuSQPVECTbqu2QGYnH anthony@Anthonys-MacBook-Pro.local', u'ssh-rsa AAAAB3NzaC1yc2EAAAADAQAB...HZj9LRfN/W3 anthony-macbookair@Affee-MacBook-Air'], u'groups': [u'sudo'], u'password': u'$1$ihlrowCw$XQCAzsSb0Zq55Nhx3jty40', u'name': u'Anthony Affee'})
ok: [127.0.0.1] => (item={u'username': u'anthony', u'uid': 2001, u'ssh_key': [u'ssh-rsa AAAAB3NzaC1yc2EAAAADAQA...PVECTbqu2QGYnH anthony@Anthonys-MacBook-Pro.local', u'ssh-rsa AAAAB3NzaC1yc2EAAAADA...B44rClNHZj9LRfN/W3 anthony-macbookair@Affee-MacBook-Air'], u'groups': [u'sudo'], u'password': u'$1$ihlrowCw$XQCAzsSb0Zq55Nhx3jty40', u'name': u'Anthony Affee'})

TASK [users : User creation] ***************************************************
failed: [wobo-web1] (item={u'username': u'anthony', u'uid': 2001, u'ssh_key': [u'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAA...CTbqu2QGYnH anthony@Anthonys-MacBook-Pro.local', u'ssh-rsa AAAAB3NzaC1yc2EAAAADAQAB...NHZj9LRfN/W3 anthony-macbookair@Affee-MacBook-Air'], u'groups': [u'sudo'], u'password': u'$1$ihlrowCw$XQCAzsSb0Zq55Nhx3jty40', u'name': u'Anthony Affee'}) => {"failed": true, "item": {"groups": ["sudo"], "name": "Anthony Affee", "password": "$1$ihlrowCw$XQCAzsSb0Zq55Nhx3jty40", "ssh_key": ["ssh-rsa AAAAB3NzaC1yc2EAAAA...VECTbqu2QGYnH anthony@Anthonys-MacBook-Pro.local", "ssh-rsa AAAAB3NzaC1yc2EAAAADAQAB...N/W3 anthony-macbookair@Affee-MacBook-Air"], "uid": 2001, "username": "anthony"}, "msg": "usermod: user anthony is currently used by process 14283\n", "name": "anthony", "rc": 8}
failed: [127.0.0.1] (item={u'username': u'anthony', u'uid': 2001, u'ssh_key': [u'ssh-rsa AAAAB3NzaC1yc2EAA...PVECTbqu2QGYnH anthony@Anthonys-MacBook-Pro.local', u'ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAA...j9LRfN/W3 anthony-macbookair@Affee-MacBook-Air'], u'groups': [u'sudo'], u'password': u'$1$ihlrowCw$XQCAzsSb0Zq55Nhx3jty40', u'name': u'Anthony Affee'}) => {"failed": true, "item": {"groups": ["sudo"], "name": "Anthony Affee", "password": "$1$ihlrowCw$XQCAzsSb0Zq55Nhx3jty40", "ssh_key": ["ssh-rsa AAAAB3Nza...QGYnH anthony@Anthonys-MacBook-Pro.local", "ssh-rsa AAAAB3NzaC1yc2EAAAA...LRfN/W3 anthony-macbookair@Affee-MacBook-Air"], "uid": 2001, "username": "anthony"}, "msg": "usermod: user anthony is currently used by process 11222\n", "name": "anthony", "rc": 8}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=3    changed=1    unreachable=0    failed=1
wobo-web1                  : ok=3    changed=1    unreachable=0    failed=1
```

```
[anthony@woodysbooks-hydra ~]$ ansible --version
ansible 2.1.1.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = Default w/o overrides
[anthony@woodysbooks-hydra ~]$ cat /etc/centos-release
CentOS release 6.8 (Final)
```

```
[anthony@woodysbooks-hydra ~]$ cat /etc/ansible/playbook/roles/users/defaults/main.yml
---
# Create a group for every user and make that their primary group
users_create_per_user_group: true
# If we're not creating a per-user group, then this is the group all users
# belong to
users_group: users
# The default shell for a user if none is specified
users_default_shell: /bin/bash
# Create home dirs for new users? Set this to false if you manage home
# directories in some other way.
users_create_homedirs: true

# Lists of users to create and delete
#users: []

users:
  - username: anthony
    name: Anthony Affee
    groups: ['sudo']
    uid: 2001
    password: $1$ih...hx3jty40
    ssh_key:
      - "ssh-rsa AAAAB3NzaC1yc2EAA...CTbqu2QGYnH anthony@Anthonys-MacBook-Pro.local"
      - "ssh-rsa AAAAB3NzaC1yc2EAAAADA...9LRfN/W3 anthony-macbookair@Affee-MacBook-Air"

users_deleted: []

# List of groups to create
# Example:
#   groups_to_create:
#     - name: developers
#       gid: 10000
#groups_to_create: []

groups_to_create:
  - name: sudo
    gid: 3001
```

I hope all the above information helps diagnose the issue. Not sure if this is a bug with Ansible or maybe the code for groups is not working with the new version.

Thanks,
Anthony
