### ISSUE TITLE
Support managing SSH private keys

### ISSUE THREAD

**Issue by FrankGiesecke** [singleplatform-eng/ansible-users#76]
When managing users with ansible, it make sense to manage the ssh private keys for a user.  
Currently, it's only possible to manage the `authorized_keys` for a user.

It might be great to define a private keys for the user.

E.g.
```yaml
users:
  - username: foo
    ssh_key:
      - <ssh public key content 1>
      - <ssh public key content 2>
    ssh_private_key: <ssh private key string>
```
